// <auto-generated />
using System;
using EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Framework.Migrations
{
    [DbContext(typeof(FacultyContext))]
    [Migration("20250813015651_SeederMahasiswaaa")]
    partial class SeederMahasiswaaa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("EntityFramework.Models.Fakultas", b =>
                {
                    b.Property<int>("FakultasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaFakultas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FakultasID");

                    b.ToTable("Fakultas");

                    b.HasData(
                        new
                        {
                            FakultasID = 1,
                            NamaFakultas = "Fakultas Teknik"
                        },
                        new
                        {
                            FakultasID = 2,
                            NamaFakultas = "Fakultas Ilmu Komputer"
                        },
                        new
                        {
                            FakultasID = 3,
                            NamaFakultas = "Fakultas Ekonomi"
                        },
                        new
                        {
                            FakultasID = 4,
                            NamaFakultas = "Fakultas Hukum"
                        },
                        new
                        {
                            FakultasID = 5,
                            NamaFakultas = "Fakultas Kedokteran"
                        },
                        new
                        {
                            FakultasID = 6,
                            NamaFakultas = "Fakultas MIPA"
                        },
                        new
                        {
                            FakultasID = 7,
                            NamaFakultas = "Fakultas Pertanian"
                        },
                        new
                        {
                            FakultasID = 8,
                            NamaFakultas = "Fakultas Psikologi"
                        },
                        new
                        {
                            FakultasID = 9,
                            NamaFakultas = "Fakultas Sastra"
                        },
                        new
                        {
                            FakultasID = 10,
                            NamaFakultas = "Fakultas Ilmu Sosial"
                        },
                        new
                        {
                            FakultasID = 11,
                            NamaFakultas = "Fakultas Ilmu Budaya"
                        },
                        new
                        {
                            FakultasID = 12,
                            NamaFakultas = "Fakultas Kesehatan Masyarakat"
                        },
                        new
                        {
                            FakultasID = 13,
                            NamaFakultas = "Fakultas Perikanan"
                        },
                        new
                        {
                            FakultasID = 14,
                            NamaFakultas = "Fakultas Peternakan"
                        },
                        new
                        {
                            FakultasID = 15,
                            NamaFakultas = "Fakultas Teknik Sipil"
                        },
                        new
                        {
                            FakultasID = 16,
                            NamaFakultas = "Fakultas Farmasi"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Mahasiswa", b =>
                {
                    b.Property<int>("MahasiswaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaMahasiswa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdiID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.HasKey("MahasiswaID");

                    b.HasIndex("ProdiID");

                    b.ToTable("Mahasiswa");

                    b.HasData(
                        new
                        {
                            MahasiswaID = 1,
                            NIM = "123456789",
                            NamaMahasiswa = "Budi",
                            ProdiID = 1,
                            TanggalLahir = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MahasiswaID = 2,
                            NIM = "987654321",
                            NamaMahasiswa = "Siti",
                            ProdiID = 1,
                            TanggalLahir = new DateTime(2001, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MahasiswaID = 3,
                            NIM = "1122334455",
                            NamaMahasiswa = "Andi",
                            ProdiID = 2,
                            TanggalLahir = new DateTime(2002, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MahasiswaID = 4,
                            NIM = "5566778899",
                            NamaMahasiswa = "Dewi",
                            ProdiID = 2,
                            TanggalLahir = new DateTime(2003, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MahasiswaID = 5,
                            NIM = "123123123",
                            NamaMahasiswa = "Driono",
                            ProdiID = 1,
                            TanggalLahir = new DateTime(2004, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.Property<int>("ProdiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FakultasID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaProdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProdiID");

                    b.HasIndex("FakultasID");

                    b.ToTable("Prodi");

                    b.HasData(
                        new
                        {
                            ProdiID = 1,
                            FakultasID = 1,
                            NamaProdi = "Teknik Elektro"
                        },
                        new
                        {
                            ProdiID = 2,
                            FakultasID = 2,
                            NamaProdi = "Sistem Informasi"
                        },
                        new
                        {
                            ProdiID = 3,
                            FakultasID = 3,
                            NamaProdi = "Manajemen"
                        },
                        new
                        {
                            ProdiID = 4,
                            FakultasID = 3,
                            NamaProdi = "Akuntansi"
                        },
                        new
                        {
                            ProdiID = 5,
                            FakultasID = 4,
                            NamaProdi = "Ilmu Hukum"
                        },
                        new
                        {
                            ProdiID = 6,
                            FakultasID = 5,
                            NamaProdi = "Kedokteran Umum"
                        },
                        new
                        {
                            ProdiID = 7,
                            FakultasID = 6,
                            NamaProdi = "Matematika"
                        },
                        new
                        {
                            ProdiID = 8,
                            FakultasID = 6,
                            NamaProdi = "Biologi"
                        },
                        new
                        {
                            ProdiID = 9,
                            FakultasID = 7,
                            NamaProdi = "Agroteknologi"
                        },
                        new
                        {
                            ProdiID = 10,
                            FakultasID = 8,
                            NamaProdi = "Psikologi"
                        },
                        new
                        {
                            ProdiID = 11,
                            FakultasID = 9,
                            NamaProdi = "Sastra Indonesia"
                        },
                        new
                        {
                            ProdiID = 12,
                            FakultasID = 10,
                            NamaProdi = "Sosiologi"
                        },
                        new
                        {
                            ProdiID = 13,
                            FakultasID = 10,
                            NamaProdi = "Ilmu Komunikasi"
                        },
                        new
                        {
                            ProdiID = 14,
                            FakultasID = 11,
                            NamaProdi = "Ilmu Budaya"
                        },
                        new
                        {
                            ProdiID = 15,
                            FakultasID = 12,
                            NamaProdi = "Kesehatan Masyarakat"
                        },
                        new
                        {
                            ProdiID = 16,
                            FakultasID = 15,
                            NamaProdi = "Teknik Sipil"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Mahasiswa", b =>
                {
                    b.HasOne("EntityFramework.Models.Prodi", "Prodi")
                        .WithMany("Mahasiswas")
                        .HasForeignKey("ProdiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodi");
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.HasOne("EntityFramework.Models.Fakultas", "Fakultas")
                        .WithMany("Prodis")
                        .HasForeignKey("FakultasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakultas");
                });

            modelBuilder.Entity("EntityFramework.Models.Fakultas", b =>
                {
                    b.Navigation("Prodis");
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.Navigation("Mahasiswas");
                });
#pragma warning restore 612, 618
        }
    }
}
