// <auto-generated />
using System;
using EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Framework.Migrations
{
    [DbContext(typeof(FacultyContext))]
    [Migration("20250812071922_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("EntityFramework.Models.Fakultas", b =>
                {
                    b.Property<int>("FakultasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaFakultas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FakultasID");

                    b.ToTable("Fakultas");
                });

            modelBuilder.Entity("EntityFramework.Models.Mahasiswa", b =>
                {
                    b.Property<int>("MahasiswaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaMahasiswa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdiID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.HasKey("MahasiswaID");

                    b.HasIndex("ProdiID");

                    b.ToTable("Mahasiswa");
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.Property<int>("ProdiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FakultasID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaProdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProdiID");

                    b.HasIndex("FakultasID");

                    b.ToTable("Prodi");
                });

            modelBuilder.Entity("EntityFramework.Models.Mahasiswa", b =>
                {
                    b.HasOne("EntityFramework.Models.Prodi", "Prodi")
                        .WithMany("Mahasiswas")
                        .HasForeignKey("ProdiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodi");
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.HasOne("EntityFramework.Models.Fakultas", "Fakultas")
                        .WithMany("Prodis")
                        .HasForeignKey("FakultasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakultas");
                });

            modelBuilder.Entity("EntityFramework.Models.Fakultas", b =>
                {
                    b.Navigation("Prodis");
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.Navigation("Mahasiswas");
                });
#pragma warning restore 612, 618
        }
    }
}
