// <auto-generated />
using System;
using EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Framework.Migrations
{
    [DbContext(typeof(FacultyContext))]
    [Migration("20250812073859_SeederMahasiswa")]
    partial class SeederMahasiswa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("EntityFramework.Models.Fakultas", b =>
                {
                    b.Property<int>("FakultasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaFakultas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FakultasID");

                    b.ToTable("Fakultas");

                    b.HasData(
                        new
                        {
                            FakultasID = 1,
                            NamaFakultas = "Fakultas Teknik"
                        },
                        new
                        {
                            FakultasID = 2,
                            NamaFakultas = "Fakultas Ilmu Komputer"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Mahasiswa", b =>
                {
                    b.Property<int>("MahasiswaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaMahasiswa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdiID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.HasKey("MahasiswaID");

                    b.HasIndex("ProdiID");

                    b.ToTable("Mahasiswa");

                    b.HasData(
                        new
                        {
                            MahasiswaID = 1,
                            NIM = "123456789",
                            NamaMahasiswa = "Budi",
                            ProdiID = 1,
                            TanggalLahir = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MahasiswaID = 2,
                            NIM = "987654321",
                            NamaMahasiswa = "Siti",
                            ProdiID = 1,
                            TanggalLahir = new DateTime(2001, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MahasiswaID = 3,
                            NIM = "1122334455",
                            NamaMahasiswa = "Andi",
                            ProdiID = 2,
                            TanggalLahir = new DateTime(2002, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MahasiswaID = 4,
                            NIM = "5566778899",
                            NamaMahasiswa = "Dewi",
                            ProdiID = 2,
                            TanggalLahir = new DateTime(2003, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.Property<int>("ProdiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FakultasID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaProdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProdiID");

                    b.HasIndex("FakultasID");

                    b.ToTable("Prodi");

                    b.HasData(
                        new
                        {
                            ProdiID = 1,
                            FakultasID = 1,
                            NamaProdi = "Teknik Elektro"
                        },
                        new
                        {
                            ProdiID = 2,
                            FakultasID = 2,
                            NamaProdi = "Sistem Informasi"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Mahasiswa", b =>
                {
                    b.HasOne("EntityFramework.Models.Prodi", "Prodi")
                        .WithMany("Mahasiswas")
                        .HasForeignKey("ProdiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodi");
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.HasOne("EntityFramework.Models.Fakultas", "Fakultas")
                        .WithMany("Prodis")
                        .HasForeignKey("FakultasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakultas");
                });

            modelBuilder.Entity("EntityFramework.Models.Fakultas", b =>
                {
                    b.Navigation("Prodis");
                });

            modelBuilder.Entity("EntityFramework.Models.Prodi", b =>
                {
                    b.Navigation("Mahasiswas");
                });
#pragma warning restore 612, 618
        }
    }
}
