// <auto-generated />
using System;
using EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD__WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250813043449_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CRUD_WebAPI.Models.Fakultas", b =>
                {
                    b.Property<int>("FakultasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaFakultas")
                        .HasColumnType("TEXT");

                    b.HasKey("FakultasID");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("CRUD_WebAPI.Models.Mahasiswa", b =>
                {
                    b.Property<int>("MahasiswaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .HasColumnType("TEXT");

                    b.Property<int>("NIM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaMahasiswa")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdiID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.HasKey("MahasiswaID");

                    b.HasIndex("ProdiID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CRUD_WebAPI.Models.Prodi", b =>
                {
                    b.Property<int>("ProdiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FakultasID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaProdi")
                        .HasColumnType("TEXT");

                    b.HasKey("ProdiID");

                    b.HasIndex("FakultasID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("CRUD_WebAPI.Models.Mahasiswa", b =>
                {
                    b.HasOne("CRUD_WebAPI.Models.Prodi", "Prodi")
                        .WithMany("Students")
                        .HasForeignKey("ProdiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodi");
                });

            modelBuilder.Entity("CRUD_WebAPI.Models.Prodi", b =>
                {
                    b.HasOne("CRUD_WebAPI.Models.Fakultas", "Fakultas")
                        .WithMany("Prodis")
                        .HasForeignKey("FakultasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakultas");
                });

            modelBuilder.Entity("CRUD_WebAPI.Models.Fakultas", b =>
                {
                    b.Navigation("Prodis");
                });

            modelBuilder.Entity("CRUD_WebAPI.Models.Prodi", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
