classDiagram
class Game {
    -List~IPlayer~ _players
    -IDiscardTiles discardTile 
    -ICard card
    %% -List~ICard~ _hand
    -Dictionary ~Player,Hand~
    +GetHand() List~ICard~
    +Action~ICard~ OnStart
    +Action OnScore
    +Game(List~IPlayer~ players)
    +StartGame() void
    +AddCard(ICard card) void
    +IsDoubleValue() void : boolean
    +IsEmpty() boolean
    +DetermineStartingPlayer() IPlayer
    +NextTurn() void
    +HasPlayableCard(IDiscardTiles discardTile) boolean
    +FindPlayableCard(IDiscardTiles discardTile) ICard
    +PlayCard(IPlayer player , ICard card , string potionCard) boolean
    +RotateValue()  void 
    +PlaceCard(ICard card, string potionCard) boolean  
    +RemoveCard(ICard card) boolean
    +CheckWinCondition() boolean
    +AddScore(int points) void
    +CalculateScore() int
    +EndGame() void
}

class Player {
    -string _name
    -int _score
    +Player(string name)
    +GetScore() int
}

class Card {
    -int _leftValueCard
    -int _rightValueCard
    +Card(int _leftValueCard , int _rightValueCard)
    +GetLeftValueCard() int
    +GetRightValueCard() int
    +GetOtherValueCard(int value) int
    +ToString() string
}

%% class Hand {
%%     -List~ICard~ _card
%%     +GetCards(): List~ICard~
    
%% }

class DiscardTile {
    -List~ICard~ _playedDominoes 
    -int _leftValueDiscardTile
    -int _rightValueDiscardTile
    +GetLeftValueDiscardTile() int
    +GetRightValueDiscardTile() int
    +GetPlayedCards() List~ICard~
}

class IDiscardTile {
    <<interface>>
    +GetLeftValueDiscardTile() int
    +GetRightValueDiscardTile() int
    +GetPlayedCards() List~ICard~

}
class IPlayer {
    <<interface>>
    +GetHand() List~ICard~
    +GetScore() int
}
class ICard {
    <<interface>>
    +GetLeftValueCard() int
    +GetRightValueCard() int
    +GetOtherValueCard(int value) int
}
%%implementasi
DiscardTile <-- IDiscardTile
Player <-- IPlayer
Card <-- ICard
%%assosiation
Game --* IPlayer
Game --* IDiscardTile
Game --* ICard
DiscardTile --* ICard
IDiscardTile --> ICard
Player --*ICard
%% Game "1" -- "*" IPlayer : contains
%% Game "1" -- "1" Board : uses
%% Player "1" -- "1" Hand : has
%% Hand "1" -- "*" Card : contains
%% Board "1" -- "*" Card : displays