classDiagram
class Game {
    -List<.Player> _players
    -board: IBoard
    -currentPlayer: IPlayer
    +Action<.Player>
    +Action<.Player,Card>
    +StartGame(int initialTilesPerPlayer): void
    +EndGame(): void
    +NextTurn(): void
    +PlayCard(IPlayer player , Card card , string potionCard): boolean
    +CheckWinCondition(): boolean
    +DetermineStartingPlayer(): IPlayer
    +IsDoubleValue(): void :boolean
    +RotateValue() : void
}

class Player {
    -string _name
    -hand: Hand
    -int _score
    +Player(string name)
    +Play(IPlayer player , Card domino , string potionCard): boolean
    +GetHand(): Hand
    +GetScore(): int
    +AddScore(int points): void
    +HasPlayableCard(IBoard board): boolean
}

class Card {
    -int _leftValue
    -int _rightValue
    +Card(int _leftValue , int _rightValue)
    +Get _leftValue(): int
    +Get _rightValu(): int
    +GetOtherEnd(int value): int
    +ToString(): string
}

class Hand {
    -List<.Card> _card
    +AddCard(Card card): void
    +RemoveCard(Card card): boolean
    +GetCards(): List<Card>
    +IsEmpty(): boolean
    +CalculateScore(): int
    +FindPlayableCard(IBoard board): Card // New method to find a playable tile
}

class Board {
    -List<.Card> _playedDominoes 
    -int _leftEnd 
    -int _rightEnd
    +PlaceCard(Card card, string potionCard): boolean
    +GetLeftEnd(): int
    +GetRightEnd(): int
    +GetPlayedCards(): List<Card>
    +IsEmpty(): boolean
}

class IBoard {
    <<interface>>
    +PlaceCard(Card card, string potionCard): boolean
    +GetLeftEnd(): int
    +GetRightEnd(): int
    +GetPlayedCards(): List<Card>
    +IsEmpty(): boolean
}
class IPlayer {
    <<interface>>
    +Play(Card card , IBoard board , string potionCard): boolean
    +GetHand(): Hand
    +GetScore(): int
    +AddScore(int points): void
    +HasPlayableCard(IBoard board): boolean
}
%%implementasi
IBoard <|.. Board
IPlayer <|.. Player
%%assosiation
Game "1" -- "*" Player : contains
Game "1" -- "1" Board : uses
Player "1" -- "1" Hand : has
Hand "1" -- "*" Card : contains
Board "1" -- "*" Card : displays